[project]
name = "rag-and-chunking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "faiss-cpu>=1.13.0",
    "sentence-transformers>=5.1.2",
    "transformers>=4.57.3",
]
